# Generated by Django 2.2 on 2020-06-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200608_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
