# Generated by Django 2.2 on 2020-06-08 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_usertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserType',
            new_name='Profile',
        ),
    ]
