# Generated by Django 2.2 on 2020-06-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplant',
            name='photo',
            field=models.FileField(upload_to='images'),
        ),
    ]
