# Generated by Django 2.2 on 2020-06-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200608_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplant',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
