# Generated by Django 2.2 on 2020-06-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20200608_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplant',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
