# Generated by Django 2.2 on 2020-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20200609_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='addplant',
            name='u_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
